### ISSUE TITLE
what about adding the recent model OpenAI GPT-2 ?

### ISSUE THREAD

**Issue by lianggaoquan** [graykode/nlp-tutorial#15]
Since the recent model OpenAI GPT-2 may be better than BERT and it would be an important breakthrough in NLP,  why not adding its' intuitive and simplest code in this repo ?

**Comment by graykode** [comment]
@lianggaoquan  Hello! I try to implement here : https://github.com/graykode/gpt-2-Pytorch
But, It is hard to convert tensorflow checkpoint file to pytorch
gpt-2 concept is not much different from the openAi-gpt.
Also, if you run gpt-2 model, https://github.com/huggingface/pytorch-pretrained-BERT this project also good Thanks :D
