### ISSUE TITLE
Seq2Seq pytorch

### ISSUE THREAD

**Issue by DonghyungKo** [graykode/nlp-tutorial#19]
Hi
thanks for sharing your codes.

I've had read your seq2seq implementation and I was wondering about the RNN Encode-Decode model.

in the paper, 'Learning Phrase Representations using RNN Encoder–Decoder
for Statistical Machine Translation' 

**They say** 

![image](https://user-images.githubusercontent.com/40687395/54875290-5f487100-4e3f-11e9-9ba0-e0e2b0d88c07.png)

**proposed gating unit**
![image](https://user-images.githubusercontent.com/40687395/54875293-6c656000-4e3f-11e9-98bc-18ad86a8d3ab.png)

and I couldn't find the new hidden-state activation function in your code.

Do you have any plan to add the proposed activation process?
or is it okay to just skip the parts?

thank you so much in advance

**Comment by graykode** [comment]
Yes. but, Contribution is always open

**Comment by DonghyungKo** [comment]
thank you 

I was just wondering whether it matters or not

straight-forward code btw, really nice work
thanks
