### ISSUE TITLE
Why is first parameter `src_vocab_size`?

### ISSUE THREAD

**Issue by yangdechuan** [graykode/nlp-tutorial#30]
https://github.com/graykode/nlp-tutorial/blob/3b3a80dc63e69935731bcf09c951eb371692af8f/5-1.Transformer/Transformer(Greedy_decoder)-Torch.py#L141

position encoding table should be (src_len, d_model). Why (src_vocab_size, d_model) here?

**Comment by graykode** [comment]
Oops.. Thanks for right catching
In Encoder `src_len+1` is right, and  as same `tgt_len+1` in Decoder
